language: php
php:
  - "5.6"
  - "5.5"

services:
  - mysql

branches:
  only:
    - master

install:
  - composer install
  - php artisan migrate --force

script:
  - phpunit tests/TwitterSearchTest.php
  - phpunit tests/TweetsCachesTest.php