language: php
php:
  - "5.6"
  - "5.5"

services:
  - mysql

branches:
  only:
    - master

before_install:
  - mysql -e "create database IF NOT EXISTS tweet_map;" -uroot

install:
  - composer install
  - php artisan migrate --force

script:
  - phpunit tests/TwitterSearchTest.php
  - phpunit tests/TweetsCachesTest.php